name: CI/CD Pipeline for user-api

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:

      # Step 1: Setup SSH Key
      - name: Setup SSH Key
        env:
          SSH_KEY: ${{ secrets.DEPLOY_KEY }}
        run: |
          echo "$SSH_KEY" | base64 --decode > GFRESHPROJECT2024.pem
          chmod 400 GFRESHPROJECT2024.pem

      # Step 2: Connect to EC2 and Pull Latest Code
      - name: Pull Latest Code from Git
        env:
          EC2_USER: ${{ secrets.DEPLOY_USER }}
          EC2_IP: ${{ secrets.DEPLOY_SERVER }}
        run: |
          ssh -i s.pem -o StrictHostKeyChecking=no $EC2_USER@$EC2_IP << 'EOF'
            cd /home/ubuntu/WEEK21
            git pull origin main
          EOF

      # Step 3: Build Go Application
      - name: Testing and Building Go Application
        env:
          EC2_USER: ${{ secrets.DEPLOY_USER }}
          EC2_IP: ${{ secrets.DEPLOY_SERVER }}
        run: |
          ssh -i s.pem -o StrictHostKeyChecking=no $EC2_USER@$EC2_IP << 'EOF'
            # Update system packages
            sudo apt update
            sudo apt install -y golang-go
            
            # Verify Go installation
            go version

            # Navigate to the project directory and build the app
            cd /home/ubuntu/WEEK21
            go mod tidy
            go test ./... -v
            go build -o user-api ./cmd/main.go
          EOF

      # Step 4: Restart Application Service
      - name: Restart Application Service
        env:
          EC2_USER: ${{ secrets.DEPLOY_USER }}
          EC2_IP: ${{ secrets.DEPLOY_SERVER }}
        run: |
          ssh -i s.pem -o StrictHostKeyChecking=no $EC2_USER@$EC2_IP << 'EOF'
            sudo systemctl restart thefurnishstore.service  
          EOF

      # Step 5: Cleanup SSH Key
      - name: Cleanup
        run: |
          rm -f GFRESHPROJECT2024.pem